### ISSUE TITLE
First time load can look like the app is frozen

### ISSUE THREAD

**Issue by joshka** [samyosm/news#1]
The initial load of categories takes a bit longer than the second load and the app looks non-responsive. I actually cancelled running it and took a look at the source to understand the reason for the delay before noting this.

Perhaps add a small message on first use?

**Comment by samyosm** [comment]
Yeah, this only applies to the very first request of the day where the server caches all the news articles. I'm thinking of adding a cron job on the server that will fetch the news at midnight.

I'll add a message just in case though.
